name: water_heater_app_flutter
description: Flutter приложение для обратного звонка
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  url_launcher: ^6.2.5
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_svg: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_novatec.svg
